DROP TABLE IF EXISTS `donation`;
CREATE TABLE IF NOT EXISTS "donation" (
  "id" int(10) unsigned NOT NULL,
  "person_id" int(11) unsigned NOT NULL default '0',
  "project_id" smallint(6) unsigned default NULL,
  "chapter_id" tinyint(4) unsigned default NULL,
  "debit_type_id" tinyint(4) unsigned default NULL,
  "currency_id" tinyint(3) unsigned default NULL,
  "privacy_type_id" tinyint(3) unsigned default NULL,
  "successful" tinyint(1) unsigned default NULL,
  "debit_type" enum('CreditCard','PaperCheck','ECheck','Other', 'GoogleWallet','Paypal') NOT NULL default 'CreditCard',
  "is_check" tinyint(1) unsigned default '0',
  "date_check" date default NULL,
  "billing_cardname" varchar(60) default NULL,
  "email" varchar(60) default NULL,
  "description" varchar(100) default NULL,
  "invoiceno" varchar(20) default NULL,
  "custno" varchar(20) default NULL,
  "password" varchar(21) default NULL,
  "billing_address" varchar(40) default NULL,
  "billing_address2" varchar(30) default NULL,
  "billing_city" varchar(30) default NULL,
  "billing_state" char(2) default NULL,
  "billing_zip" varchar(10) default NULL,
  "billing_country" smallint(6) default NULL,
  "billing_amount" decimal(6,2) default NULL,
  "billing_cardtype" varchar(10) default NULL,
  "billing_cardnum" varchar(16) default NULL,
  "billing_expires" varchar(6) default NULL,
  "billing_cvv2" varchar(4) default NULL,
  "phone" varchar(30) default NULL,
  "fax" varchar(30) default NULL,
  "receipt" tinyint(1) unsigned default NULL,
  "date_sent" date default NULL,
  "how_heard" varchar(30) default NULL,
  "referral" varchar(75) default NULL,
  "http_ref" varchar(120) default NULL,
  "organization" varchar(75) default NULL,
  "join_list" tinyint(1) default NULL,
  "company_id" smallint(6) default NULL,
  "comments" text,
  "notes" text,
  "last_modified" timestamp NOT NULL default CURRENT_TIMESTAMP,
  "date_added" timestamp NOT NULL default '0000-00-00 00:00:00',
  "responsecode" varchar(12) default NULL,
  "authresponse" varchar(120) default NULL,
  "approvalcode" varchar(21) default NULL,
  "replycode" varchar(30) default NULL,
  "authsource" tinyint(4) default NULL,
  "capcode" tinyint(4) default NULL,
  "amexcapcode" tinyint(4) default NULL,
  "transdate" varchar(12) default NULL,
  "transtime" varchar(12) default NULL,
  "avsresponse" varchar(30) default NULL,
  "cvv2response" varchar(30) default NULL,
  "post_url" varchar(60) default NULL,
  "post_http_code" int(11) default NULL,
  "post_header_size" int(11) default NULL,
  "post_request_size" int(11) default NULL,
  "post_filetime" int(11) default NULL,
  "post_ssl_verify_result" int(11) default NULL,
  "post_total_time" decimal(10,3) default NULL,
  "post_namelookup_time" decimal(10,3) default NULL,
  "post_connect_time" decimal(10,3) default NULL,
  "post_pretransfer_time" decimal(10,3) default NULL,
  "post_size_upload" int(11) default NULL,
  "post_size_download" int(11) default NULL,
  "post_speed_download" decimal(20,10) default NULL,
  "post_speed_upload" decimal(20,10) default NULL,
  "post_download_content_length" int(11) default NULL,
  "post_upload_content_length" int(11) default NULL,
  "event_id" smallint(5) unsigned default NULL,
  "channel_id" smallint(5) unsigned default NULL,
  "cart" varchar(120) default NULL,
  "ip" varchar(30) default NULL,
  "host" varchar(60) default NULL,
  PRIMARY KEY  ("id","person_id"),
  UNIQUE KEY "id" ("id")
) AUTO_INCREMENT=1 ;
